/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivityTimelineEventRecord } from "./components/business-widgets/activity-timeline/shared/activity-timeline-utils";
import { ActivityTimelineEventRecord as ActivityTimelineEventRecord1, ActivityTimelineEventTone } from "./components/business-widgets/activity-timeline/shared/activity-timeline-types";
import { CalendarEventRecord, CalendarNavigateAction, CalendarTone, CalendarView, CalendarWeekday } from "./components/business-widgets/calendar/shared/calendar-utils";
import { ChecklistItemRecord } from "./components/business-widgets/checklist/shared/checklist-utils";
import { ChecklistItemRecord as ChecklistItemRecord1, ChecklistItemTone } from "./components/business-widgets/checklist/shared/checklist-types";
import { KanbanColumnRecord } from "./components/business-widgets/kanban/shared/kanban-utils";
import { KanbanCardRecord, KanbanCardTone } from "./components/business-widgets/kanban/shared/kanban-types";
import { UiSelectOptionRecord } from "./components/primitives/shared/form-utils";
import { TaskListItemRecord } from "./components/business-widgets/task-list/shared/task-list-utils";
import { TaskListItemRecord as TaskListItemRecord1, TaskListItemTone } from "./components/business-widgets/task-list/shared/task-list-types";
export { ActivityTimelineEventRecord } from "./components/business-widgets/activity-timeline/shared/activity-timeline-utils";
export { ActivityTimelineEventRecord as ActivityTimelineEventRecord1, ActivityTimelineEventTone } from "./components/business-widgets/activity-timeline/shared/activity-timeline-types";
export { CalendarEventRecord, CalendarNavigateAction, CalendarTone, CalendarView, CalendarWeekday } from "./components/business-widgets/calendar/shared/calendar-utils";
export { ChecklistItemRecord } from "./components/business-widgets/checklist/shared/checklist-utils";
export { ChecklistItemRecord as ChecklistItemRecord1, ChecklistItemTone } from "./components/business-widgets/checklist/shared/checklist-types";
export { KanbanColumnRecord } from "./components/business-widgets/kanban/shared/kanban-utils";
export { KanbanCardRecord, KanbanCardTone } from "./components/business-widgets/kanban/shared/kanban-types";
export { UiSelectOptionRecord } from "./components/primitives/shared/form-utils";
export { TaskListItemRecord } from "./components/business-widgets/task-list/shared/task-list-utils";
export { TaskListItemRecord as TaskListItemRecord1, TaskListItemTone } from "./components/business-widgets/task-list/shared/task-list-types";
export namespace Components {
    interface UiActivityTimeline {
        /**
          * @default []
         */
        "events": ActivityTimelineEventRecord[];
        /**
          * @default 'Activity timeline'
         */
        "label": string;
    }
    interface UiActivityTimelineItem {
        "event": ActivityTimelineEventRecord1;
        /**
          * @default 'neutral'
         */
        "tone": ActivityTimelineEventTone;
    }
    interface UiBadge {
        /**
          * @default 'neutral'
         */
        "tone": 'neutral' | 'accent';
    }
    interface UiButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "pressed"?: boolean;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface UiCalendar {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate": string;
        /**
          * @default []
         */
        "events": CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek": CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale": string;
        "selectedDate"?: string;
        /**
          * @default 'month'
         */
        "view": CalendarView;
    }
    interface UiCalendarDayCell {
        /**
          * @default ''
         */
        "date": string;
        /**
          * @default 0
         */
        "dayNumber": number;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default false
         */
        "outsideMonth": boolean;
        /**
          * @default false
         */
        "selected": boolean;
        /**
          * @default false
         */
        "today": boolean;
    }
    interface UiCalendarDayView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate": string;
        /**
          * @default []
         */
        "events": CalendarEventRecord[];
        /**
          * @default 'en-US'
         */
        "locale": string;
        "selectedDate"?: string;
    }
    interface UiCalendarEventChip {
        /**
          * @default ''
         */
        "date": string;
        "event": CalendarEventRecord;
        /**
          * @default 'neutral'
         */
        "tone": CalendarTone;
    }
    interface UiCalendarMonthView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate": string;
        /**
          * @default []
         */
        "events": CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek": CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale": string;
        "selectedDate"?: string;
    }
    interface UiCalendarToolbar {
        /**
          * @default ''
         */
        "rangeLabel": string;
    }
    interface UiCalendarWeekView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate": string;
        /**
          * @default []
         */
        "events": CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek": CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale": string;
        "selectedDate"?: string;
    }
    interface UiCard {
        /**
          * @default 'surface'
         */
        "tone": 'surface' | 'accent';
    }
    interface UiChecklist {
        /**
          * @default []
         */
        "items": ChecklistItemRecord[];
        /**
          * @default 'Checklist'
         */
        "label": string;
    }
    interface UiChecklistItem {
        /**
          * @default false
         */
        "completed": boolean;
        "item": ChecklistItemRecord1;
        /**
          * @default 'neutral'
         */
        "tone": ChecklistItemTone;
    }
    interface UiChip {
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "tone": 'neutral' | 'accent';
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiKanbanBoard {
        /**
          * @default []
         */
        "columns": KanbanColumnRecord[];
    }
    interface UiKanbanCard {
        "card": KanbanCardRecord;
        /**
          * @default ''
         */
        "columnId": string;
        /**
          * @default 'neutral'
         */
        "tone": KanbanCardTone;
    }
    interface UiKanbanColumn {
        /**
          * @default 0
         */
        "cardCount": number;
        /**
          * @default []
         */
        "cards": KanbanCardRecord[];
        /**
          * @default ''
         */
        "columnId": string;
        /**
          * @default ''
         */
        "columnTitle": string;
    }
    interface UiPageSection {
    }
    interface UiPanel {
        /**
          * @default 'surface'
         */
        "tone": 'surface' | 'accent';
    }
    interface UiSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default []
         */
        "options": UiSelectOptionRecord[];
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiStack {
        /**
          * @default 'md'
         */
        "space": 'sm' | 'md' | 'lg';
    }
    interface UiTaskList {
        /**
          * @default []
         */
        "items": TaskListItemRecord[];
        /**
          * @default 'Task list'
         */
        "label": string;
    }
    interface UiTaskListItem {
        "item": TaskListItemRecord1;
        /**
          * @default 'neutral'
         */
        "tone": TaskListItemTone;
    }
    interface UiTextarea {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "hint": string;
        /**
          * @default false
         */
        "invalid": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 5
         */
        "rows": number;
        /**
          * @default ''
         */
        "value": string;
    }
    interface UiToolbar {
        /**
          * @default 'between'
         */
        "justify": 'start' | 'between' | 'center';
    }
}
export interface UiCalendarDayCellCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCalendarDayCellElement;
}
export interface UiCalendarDayViewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCalendarDayViewElement;
}
export interface UiCalendarEventChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCalendarEventChipElement;
}
export interface UiCalendarToolbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiCalendarToolbarElement;
}
export interface UiChecklistItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiChecklistItemElement;
}
export interface UiInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiInputElement;
}
export interface UiKanbanCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiKanbanCardElement;
}
export interface UiSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiSelectElement;
}
export interface UiTaskListItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiTaskListItemElement;
}
export interface UiTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUiTextareaElement;
}
declare global {
    interface HTMLUiActivityTimelineElement extends Components.UiActivityTimeline, HTMLStencilElement {
    }
    var HTMLUiActivityTimelineElement: {
        prototype: HTMLUiActivityTimelineElement;
        new (): HTMLUiActivityTimelineElement;
    };
    interface HTMLUiActivityTimelineItemElement extends Components.UiActivityTimelineItem, HTMLStencilElement {
    }
    var HTMLUiActivityTimelineItemElement: {
        prototype: HTMLUiActivityTimelineItemElement;
        new (): HTMLUiActivityTimelineItemElement;
    };
    interface HTMLUiBadgeElement extends Components.UiBadge, HTMLStencilElement {
    }
    var HTMLUiBadgeElement: {
        prototype: HTMLUiBadgeElement;
        new (): HTMLUiBadgeElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCalendarElement extends Components.UiCalendar, HTMLStencilElement {
    }
    var HTMLUiCalendarElement: {
        prototype: HTMLUiCalendarElement;
        new (): HTMLUiCalendarElement;
    };
    interface HTMLUiCalendarDayCellElementEventMap {
        "uiCalendarDateSelect": { date: string };
    }
    interface HTMLUiCalendarDayCellElement extends Components.UiCalendarDayCell, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCalendarDayCellElementEventMap>(type: K, listener: (this: HTMLUiCalendarDayCellElement, ev: UiCalendarDayCellCustomEvent<HTMLUiCalendarDayCellElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCalendarDayCellElementEventMap>(type: K, listener: (this: HTMLUiCalendarDayCellElement, ev: UiCalendarDayCellCustomEvent<HTMLUiCalendarDayCellElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCalendarDayCellElement: {
        prototype: HTMLUiCalendarDayCellElement;
        new (): HTMLUiCalendarDayCellElement;
    };
    interface HTMLUiCalendarDayViewElementEventMap {
        "uiCalendarDateSelect": { date: string };
    }
    interface HTMLUiCalendarDayViewElement extends Components.UiCalendarDayView, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCalendarDayViewElementEventMap>(type: K, listener: (this: HTMLUiCalendarDayViewElement, ev: UiCalendarDayViewCustomEvent<HTMLUiCalendarDayViewElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCalendarDayViewElementEventMap>(type: K, listener: (this: HTMLUiCalendarDayViewElement, ev: UiCalendarDayViewCustomEvent<HTMLUiCalendarDayViewElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCalendarDayViewElement: {
        prototype: HTMLUiCalendarDayViewElement;
        new (): HTMLUiCalendarDayViewElement;
    };
    interface HTMLUiCalendarEventChipElementEventMap {
        "uiCalendarEventActivate": { event: CalendarEventRecord; date: string };
    }
    interface HTMLUiCalendarEventChipElement extends Components.UiCalendarEventChip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCalendarEventChipElementEventMap>(type: K, listener: (this: HTMLUiCalendarEventChipElement, ev: UiCalendarEventChipCustomEvent<HTMLUiCalendarEventChipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCalendarEventChipElementEventMap>(type: K, listener: (this: HTMLUiCalendarEventChipElement, ev: UiCalendarEventChipCustomEvent<HTMLUiCalendarEventChipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCalendarEventChipElement: {
        prototype: HTMLUiCalendarEventChipElement;
        new (): HTMLUiCalendarEventChipElement;
    };
    interface HTMLUiCalendarMonthViewElement extends Components.UiCalendarMonthView, HTMLStencilElement {
    }
    var HTMLUiCalendarMonthViewElement: {
        prototype: HTMLUiCalendarMonthViewElement;
        new (): HTMLUiCalendarMonthViewElement;
    };
    interface HTMLUiCalendarToolbarElementEventMap {
        "uiCalendarNavigate": { direction: CalendarNavigateAction };
    }
    interface HTMLUiCalendarToolbarElement extends Components.UiCalendarToolbar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiCalendarToolbarElementEventMap>(type: K, listener: (this: HTMLUiCalendarToolbarElement, ev: UiCalendarToolbarCustomEvent<HTMLUiCalendarToolbarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiCalendarToolbarElementEventMap>(type: K, listener: (this: HTMLUiCalendarToolbarElement, ev: UiCalendarToolbarCustomEvent<HTMLUiCalendarToolbarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiCalendarToolbarElement: {
        prototype: HTMLUiCalendarToolbarElement;
        new (): HTMLUiCalendarToolbarElement;
    };
    interface HTMLUiCalendarWeekViewElement extends Components.UiCalendarWeekView, HTMLStencilElement {
    }
    var HTMLUiCalendarWeekViewElement: {
        prototype: HTMLUiCalendarWeekViewElement;
        new (): HTMLUiCalendarWeekViewElement;
    };
    interface HTMLUiCardElement extends Components.UiCard, HTMLStencilElement {
    }
    var HTMLUiCardElement: {
        prototype: HTMLUiCardElement;
        new (): HTMLUiCardElement;
    };
    interface HTMLUiChecklistElement extends Components.UiChecklist, HTMLStencilElement {
    }
    var HTMLUiChecklistElement: {
        prototype: HTMLUiChecklistElement;
        new (): HTMLUiChecklistElement;
    };
    interface HTMLUiChecklistItemElementEventMap {
        "uiChecklistItemToggle": { item: ChecklistItemRecord1; nextCompleted: boolean };
    }
    interface HTMLUiChecklistItemElement extends Components.UiChecklistItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiChecklistItemElementEventMap>(type: K, listener: (this: HTMLUiChecklistItemElement, ev: UiChecklistItemCustomEvent<HTMLUiChecklistItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiChecklistItemElementEventMap>(type: K, listener: (this: HTMLUiChecklistItemElement, ev: UiChecklistItemCustomEvent<HTMLUiChecklistItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiChecklistItemElement: {
        prototype: HTMLUiChecklistItemElement;
        new (): HTMLUiChecklistItemElement;
    };
    interface HTMLUiChipElement extends Components.UiChip, HTMLStencilElement {
    }
    var HTMLUiChipElement: {
        prototype: HTMLUiChipElement;
        new (): HTMLUiChipElement;
    };
    interface HTMLUiInputElementEventMap {
        "uiFieldInput": { name: string; value: string };
        "uiFieldChange": { name: string; value: string };
    }
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiInputElementEventMap>(type: K, listener: (this: HTMLUiInputElement, ev: UiInputCustomEvent<HTMLUiInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiKanbanBoardElement extends Components.UiKanbanBoard, HTMLStencilElement {
    }
    var HTMLUiKanbanBoardElement: {
        prototype: HTMLUiKanbanBoardElement;
        new (): HTMLUiKanbanBoardElement;
    };
    interface HTMLUiKanbanCardElementEventMap {
        "uiKanbanCardActivate": { columnId: string; card: KanbanCardRecord };
    }
    interface HTMLUiKanbanCardElement extends Components.UiKanbanCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiKanbanCardElementEventMap>(type: K, listener: (this: HTMLUiKanbanCardElement, ev: UiKanbanCardCustomEvent<HTMLUiKanbanCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiKanbanCardElementEventMap>(type: K, listener: (this: HTMLUiKanbanCardElement, ev: UiKanbanCardCustomEvent<HTMLUiKanbanCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiKanbanCardElement: {
        prototype: HTMLUiKanbanCardElement;
        new (): HTMLUiKanbanCardElement;
    };
    interface HTMLUiKanbanColumnElement extends Components.UiKanbanColumn, HTMLStencilElement {
    }
    var HTMLUiKanbanColumnElement: {
        prototype: HTMLUiKanbanColumnElement;
        new (): HTMLUiKanbanColumnElement;
    };
    interface HTMLUiPageSectionElement extends Components.UiPageSection, HTMLStencilElement {
    }
    var HTMLUiPageSectionElement: {
        prototype: HTMLUiPageSectionElement;
        new (): HTMLUiPageSectionElement;
    };
    interface HTMLUiPanelElement extends Components.UiPanel, HTMLStencilElement {
    }
    var HTMLUiPanelElement: {
        prototype: HTMLUiPanelElement;
        new (): HTMLUiPanelElement;
    };
    interface HTMLUiSelectElementEventMap {
        "uiFieldInput": { name: string; value: string };
        "uiFieldChange": { name: string; value: string };
    }
    interface HTMLUiSelectElement extends Components.UiSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiSelectElementEventMap>(type: K, listener: (this: HTMLUiSelectElement, ev: UiSelectCustomEvent<HTMLUiSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiSelectElement: {
        prototype: HTMLUiSelectElement;
        new (): HTMLUiSelectElement;
    };
    interface HTMLUiStackElement extends Components.UiStack, HTMLStencilElement {
    }
    var HTMLUiStackElement: {
        prototype: HTMLUiStackElement;
        new (): HTMLUiStackElement;
    };
    interface HTMLUiTaskListElement extends Components.UiTaskList, HTMLStencilElement {
    }
    var HTMLUiTaskListElement: {
        prototype: HTMLUiTaskListElement;
        new (): HTMLUiTaskListElement;
    };
    interface HTMLUiTaskListItemElementEventMap {
        "uiTaskListItemActivate": { item: TaskListItemRecord1 };
    }
    interface HTMLUiTaskListItemElement extends Components.UiTaskListItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiTaskListItemElementEventMap>(type: K, listener: (this: HTMLUiTaskListItemElement, ev: UiTaskListItemCustomEvent<HTMLUiTaskListItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiTaskListItemElementEventMap>(type: K, listener: (this: HTMLUiTaskListItemElement, ev: UiTaskListItemCustomEvent<HTMLUiTaskListItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiTaskListItemElement: {
        prototype: HTMLUiTaskListItemElement;
        new (): HTMLUiTaskListItemElement;
    };
    interface HTMLUiTextareaElementEventMap {
        "uiFieldInput": { name: string; value: string };
        "uiFieldChange": { name: string; value: string };
    }
    interface HTMLUiTextareaElement extends Components.UiTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLUiTextareaElementEventMap>(type: K, listener: (this: HTMLUiTextareaElement, ev: UiTextareaCustomEvent<HTMLUiTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLUiTextareaElementEventMap>(type: K, listener: (this: HTMLUiTextareaElement, ev: UiTextareaCustomEvent<HTMLUiTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLUiTextareaElement: {
        prototype: HTMLUiTextareaElement;
        new (): HTMLUiTextareaElement;
    };
    interface HTMLUiToolbarElement extends Components.UiToolbar, HTMLStencilElement {
    }
    var HTMLUiToolbarElement: {
        prototype: HTMLUiToolbarElement;
        new (): HTMLUiToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "ui-activity-timeline": HTMLUiActivityTimelineElement;
        "ui-activity-timeline-item": HTMLUiActivityTimelineItemElement;
        "ui-badge": HTMLUiBadgeElement;
        "ui-button": HTMLUiButtonElement;
        "ui-calendar": HTMLUiCalendarElement;
        "ui-calendar-day-cell": HTMLUiCalendarDayCellElement;
        "ui-calendar-day-view": HTMLUiCalendarDayViewElement;
        "ui-calendar-event-chip": HTMLUiCalendarEventChipElement;
        "ui-calendar-month-view": HTMLUiCalendarMonthViewElement;
        "ui-calendar-toolbar": HTMLUiCalendarToolbarElement;
        "ui-calendar-week-view": HTMLUiCalendarWeekViewElement;
        "ui-card": HTMLUiCardElement;
        "ui-checklist": HTMLUiChecklistElement;
        "ui-checklist-item": HTMLUiChecklistItemElement;
        "ui-chip": HTMLUiChipElement;
        "ui-input": HTMLUiInputElement;
        "ui-kanban-board": HTMLUiKanbanBoardElement;
        "ui-kanban-card": HTMLUiKanbanCardElement;
        "ui-kanban-column": HTMLUiKanbanColumnElement;
        "ui-page-section": HTMLUiPageSectionElement;
        "ui-panel": HTMLUiPanelElement;
        "ui-select": HTMLUiSelectElement;
        "ui-stack": HTMLUiStackElement;
        "ui-task-list": HTMLUiTaskListElement;
        "ui-task-list-item": HTMLUiTaskListItemElement;
        "ui-textarea": HTMLUiTextareaElement;
        "ui-toolbar": HTMLUiToolbarElement;
    }
}
declare namespace LocalJSX {
    interface UiActivityTimeline {
        /**
          * @default []
         */
        "events"?: ActivityTimelineEventRecord[];
        /**
          * @default 'Activity timeline'
         */
        "label"?: string;
    }
    interface UiActivityTimelineItem {
        "event": ActivityTimelineEventRecord1;
        /**
          * @default 'neutral'
         */
        "tone"?: ActivityTimelineEventTone;
    }
    interface UiBadge {
        /**
          * @default 'neutral'
         */
        "tone"?: 'neutral' | 'accent';
    }
    interface UiButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "pressed"?: boolean;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'secondary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface UiCalendar {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate"?: string;
        /**
          * @default []
         */
        "events"?: CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek"?: CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        "selectedDate"?: string;
        /**
          * @default 'month'
         */
        "view"?: CalendarView;
    }
    interface UiCalendarDayCell {
        /**
          * @default ''
         */
        "date"?: string;
        /**
          * @default 0
         */
        "dayNumber"?: number;
        /**
          * @default ''
         */
        "label"?: string;
        "onUiCalendarDateSelect"?: (event: UiCalendarDayCellCustomEvent<{ date: string }>) => void;
        /**
          * @default false
         */
        "outsideMonth"?: boolean;
        /**
          * @default false
         */
        "selected"?: boolean;
        /**
          * @default false
         */
        "today"?: boolean;
    }
    interface UiCalendarDayView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate"?: string;
        /**
          * @default []
         */
        "events"?: CalendarEventRecord[];
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        "onUiCalendarDateSelect"?: (event: UiCalendarDayViewCustomEvent<{ date: string }>) => void;
        "selectedDate"?: string;
    }
    interface UiCalendarEventChip {
        /**
          * @default ''
         */
        "date"?: string;
        "event": CalendarEventRecord;
        "onUiCalendarEventActivate"?: (event: UiCalendarEventChipCustomEvent<{ event: CalendarEventRecord; date: string }>) => void;
        /**
          * @default 'neutral'
         */
        "tone"?: CalendarTone;
    }
    interface UiCalendarMonthView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate"?: string;
        /**
          * @default []
         */
        "events"?: CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek"?: CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        "selectedDate"?: string;
    }
    interface UiCalendarToolbar {
        "onUiCalendarNavigate"?: (event: UiCalendarToolbarCustomEvent<{ direction: CalendarNavigateAction }>) => void;
        /**
          * @default ''
         */
        "rangeLabel"?: string;
    }
    interface UiCalendarWeekView {
        /**
          * @default new Date().toISOString().slice(0, 10)
         */
        "anchorDate"?: string;
        /**
          * @default []
         */
        "events"?: CalendarEventRecord[];
        /**
          * @default 0
         */
        "firstDayOfWeek"?: CalendarWeekday;
        /**
          * @default 'en-US'
         */
        "locale"?: string;
        "selectedDate"?: string;
    }
    interface UiCard {
        /**
          * @default 'surface'
         */
        "tone"?: 'surface' | 'accent';
    }
    interface UiChecklist {
        /**
          * @default []
         */
        "items"?: ChecklistItemRecord[];
        /**
          * @default 'Checklist'
         */
        "label"?: string;
    }
    interface UiChecklistItem {
        /**
          * @default false
         */
        "completed"?: boolean;
        "item": ChecklistItemRecord1;
        "onUiChecklistItemToggle"?: (event: UiChecklistItemCustomEvent<{ item: ChecklistItemRecord1; nextCompleted: boolean }>) => void;
        /**
          * @default 'neutral'
         */
        "tone"?: ChecklistItemTone;
    }
    interface UiChip {
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "tone"?: 'neutral' | 'accent';
    }
    interface UiInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUiFieldChange"?: (event: UiInputCustomEvent<{ name: string; value: string }>) => void;
        "onUiFieldInput"?: (event: UiInputCustomEvent<{ name: string; value: string }>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiKanbanBoard {
        /**
          * @default []
         */
        "columns"?: KanbanColumnRecord[];
    }
    interface UiKanbanCard {
        "card": KanbanCardRecord;
        /**
          * @default ''
         */
        "columnId"?: string;
        "onUiKanbanCardActivate"?: (event: UiKanbanCardCustomEvent<{ columnId: string; card: KanbanCardRecord }>) => void;
        /**
          * @default 'neutral'
         */
        "tone"?: KanbanCardTone;
    }
    interface UiKanbanColumn {
        /**
          * @default 0
         */
        "cardCount"?: number;
        /**
          * @default []
         */
        "cards"?: KanbanCardRecord[];
        /**
          * @default ''
         */
        "columnId"?: string;
        /**
          * @default ''
         */
        "columnTitle"?: string;
    }
    interface UiPageSection {
    }
    interface UiPanel {
        /**
          * @default 'surface'
         */
        "tone"?: 'surface' | 'accent';
    }
    interface UiSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUiFieldChange"?: (event: UiSelectCustomEvent<{ name: string; value: string }>) => void;
        "onUiFieldInput"?: (event: UiSelectCustomEvent<{ name: string; value: string }>) => void;
        /**
          * @default []
         */
        "options"?: UiSelectOptionRecord[];
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiStack {
        /**
          * @default 'md'
         */
        "space"?: 'sm' | 'md' | 'lg';
    }
    interface UiTaskList {
        /**
          * @default []
         */
        "items"?: TaskListItemRecord[];
        /**
          * @default 'Task list'
         */
        "label"?: string;
    }
    interface UiTaskListItem {
        "item": TaskListItemRecord1;
        "onUiTaskListItemActivate"?: (event: UiTaskListItemCustomEvent<{ item: TaskListItemRecord1 }>) => void;
        /**
          * @default 'neutral'
         */
        "tone"?: TaskListItemTone;
    }
    interface UiTextarea {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "hint"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onUiFieldChange"?: (event: UiTextareaCustomEvent<{ name: string; value: string }>) => void;
        "onUiFieldInput"?: (event: UiTextareaCustomEvent<{ name: string; value: string }>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 5
         */
        "rows"?: number;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface UiToolbar {
        /**
          * @default 'between'
         */
        "justify"?: 'start' | 'between' | 'center';
    }

    interface UiActivityTimelineAttributes {
        "label": string;
    }
    interface UiActivityTimelineItemAttributes {
        "tone": ActivityTimelineEventTone;
    }
    interface UiBadgeAttributes {
        "tone": 'neutral' | 'accent';
    }
    interface UiButtonAttributes {
        "variant": 'primary' | 'secondary';
        "type": 'button' | 'submit' | 'reset';
        "disabled": boolean;
        "pressed": boolean;
    }
    interface UiCalendarAttributes {
        "view": CalendarView;
        "anchorDate": string;
        "selectedDate": string;
        "locale": string;
        "firstDayOfWeek": CalendarWeekday;
    }
    interface UiCalendarDayCellAttributes {
        "date": string;
        "dayNumber": number;
        "label": string;
        "today": boolean;
        "selected": boolean;
        "outsideMonth": boolean;
    }
    interface UiCalendarDayViewAttributes {
        "anchorDate": string;
        "selectedDate": string;
        "locale": string;
    }
    interface UiCalendarEventChipAttributes {
        "date": string;
        "tone": CalendarTone;
    }
    interface UiCalendarMonthViewAttributes {
        "anchorDate": string;
        "selectedDate": string;
        "locale": string;
        "firstDayOfWeek": CalendarWeekday;
    }
    interface UiCalendarToolbarAttributes {
        "rangeLabel": string;
    }
    interface UiCalendarWeekViewAttributes {
        "anchorDate": string;
        "selectedDate": string;
        "locale": string;
        "firstDayOfWeek": CalendarWeekday;
    }
    interface UiCardAttributes {
        "tone": 'surface' | 'accent';
    }
    interface UiChecklistAttributes {
        "label": string;
    }
    interface UiChecklistItemAttributes {
        "tone": ChecklistItemTone;
        "completed": boolean;
    }
    interface UiChipAttributes {
        "label": string;
        "tone": 'neutral' | 'accent';
    }
    interface UiInputAttributes {
        "label": string;
        "name": string;
        "type": 'text' | 'email' | 'password' | 'search' | 'tel' | 'url';
        "value": string;
        "placeholder": string;
        "hint": string;
        "message": string;
        "required": boolean;
        "disabled": boolean;
        "invalid": boolean;
    }
    interface UiKanbanCardAttributes {
        "columnId": string;
        "tone": KanbanCardTone;
    }
    interface UiKanbanColumnAttributes {
        "columnId": string;
        "columnTitle": string;
        "cardCount": number;
    }
    interface UiPanelAttributes {
        "tone": 'surface' | 'accent';
    }
    interface UiSelectAttributes {
        "label": string;
        "name": string;
        "value": string;
        "hint": string;
        "message": string;
        "placeholder": string;
        "required": boolean;
        "disabled": boolean;
        "invalid": boolean;
    }
    interface UiStackAttributes {
        "space": 'sm' | 'md' | 'lg';
    }
    interface UiTaskListAttributes {
        "label": string;
    }
    interface UiTaskListItemAttributes {
        "tone": TaskListItemTone;
    }
    interface UiTextareaAttributes {
        "label": string;
        "name": string;
        "value": string;
        "placeholder": string;
        "hint": string;
        "message": string;
        "rows": number;
        "required": boolean;
        "disabled": boolean;
        "invalid": boolean;
    }
    interface UiToolbarAttributes {
        "justify": 'start' | 'between' | 'center';
    }

    interface IntrinsicElements {
        "ui-activity-timeline": Omit<UiActivityTimeline, keyof UiActivityTimelineAttributes> & { [K in keyof UiActivityTimeline & keyof UiActivityTimelineAttributes]?: UiActivityTimeline[K] } & { [K in keyof UiActivityTimeline & keyof UiActivityTimelineAttributes as `attr:${K}`]?: UiActivityTimelineAttributes[K] } & { [K in keyof UiActivityTimeline & keyof UiActivityTimelineAttributes as `prop:${K}`]?: UiActivityTimeline[K] };
        "ui-activity-timeline-item": Omit<UiActivityTimelineItem, keyof UiActivityTimelineItemAttributes> & { [K in keyof UiActivityTimelineItem & keyof UiActivityTimelineItemAttributes]?: UiActivityTimelineItem[K] } & { [K in keyof UiActivityTimelineItem & keyof UiActivityTimelineItemAttributes as `attr:${K}`]?: UiActivityTimelineItemAttributes[K] } & { [K in keyof UiActivityTimelineItem & keyof UiActivityTimelineItemAttributes as `prop:${K}`]?: UiActivityTimelineItem[K] };
        "ui-badge": Omit<UiBadge, keyof UiBadgeAttributes> & { [K in keyof UiBadge & keyof UiBadgeAttributes]?: UiBadge[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `attr:${K}`]?: UiBadgeAttributes[K] } & { [K in keyof UiBadge & keyof UiBadgeAttributes as `prop:${K}`]?: UiBadge[K] };
        "ui-button": Omit<UiButton, keyof UiButtonAttributes> & { [K in keyof UiButton & keyof UiButtonAttributes]?: UiButton[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `attr:${K}`]?: UiButtonAttributes[K] } & { [K in keyof UiButton & keyof UiButtonAttributes as `prop:${K}`]?: UiButton[K] };
        "ui-calendar": Omit<UiCalendar, keyof UiCalendarAttributes> & { [K in keyof UiCalendar & keyof UiCalendarAttributes]?: UiCalendar[K] } & { [K in keyof UiCalendar & keyof UiCalendarAttributes as `attr:${K}`]?: UiCalendarAttributes[K] } & { [K in keyof UiCalendar & keyof UiCalendarAttributes as `prop:${K}`]?: UiCalendar[K] };
        "ui-calendar-day-cell": Omit<UiCalendarDayCell, keyof UiCalendarDayCellAttributes> & { [K in keyof UiCalendarDayCell & keyof UiCalendarDayCellAttributes]?: UiCalendarDayCell[K] } & { [K in keyof UiCalendarDayCell & keyof UiCalendarDayCellAttributes as `attr:${K}`]?: UiCalendarDayCellAttributes[K] } & { [K in keyof UiCalendarDayCell & keyof UiCalendarDayCellAttributes as `prop:${K}`]?: UiCalendarDayCell[K] };
        "ui-calendar-day-view": Omit<UiCalendarDayView, keyof UiCalendarDayViewAttributes> & { [K in keyof UiCalendarDayView & keyof UiCalendarDayViewAttributes]?: UiCalendarDayView[K] } & { [K in keyof UiCalendarDayView & keyof UiCalendarDayViewAttributes as `attr:${K}`]?: UiCalendarDayViewAttributes[K] } & { [K in keyof UiCalendarDayView & keyof UiCalendarDayViewAttributes as `prop:${K}`]?: UiCalendarDayView[K] };
        "ui-calendar-event-chip": Omit<UiCalendarEventChip, keyof UiCalendarEventChipAttributes> & { [K in keyof UiCalendarEventChip & keyof UiCalendarEventChipAttributes]?: UiCalendarEventChip[K] } & { [K in keyof UiCalendarEventChip & keyof UiCalendarEventChipAttributes as `attr:${K}`]?: UiCalendarEventChipAttributes[K] } & { [K in keyof UiCalendarEventChip & keyof UiCalendarEventChipAttributes as `prop:${K}`]?: UiCalendarEventChip[K] };
        "ui-calendar-month-view": Omit<UiCalendarMonthView, keyof UiCalendarMonthViewAttributes> & { [K in keyof UiCalendarMonthView & keyof UiCalendarMonthViewAttributes]?: UiCalendarMonthView[K] } & { [K in keyof UiCalendarMonthView & keyof UiCalendarMonthViewAttributes as `attr:${K}`]?: UiCalendarMonthViewAttributes[K] } & { [K in keyof UiCalendarMonthView & keyof UiCalendarMonthViewAttributes as `prop:${K}`]?: UiCalendarMonthView[K] };
        "ui-calendar-toolbar": Omit<UiCalendarToolbar, keyof UiCalendarToolbarAttributes> & { [K in keyof UiCalendarToolbar & keyof UiCalendarToolbarAttributes]?: UiCalendarToolbar[K] } & { [K in keyof UiCalendarToolbar & keyof UiCalendarToolbarAttributes as `attr:${K}`]?: UiCalendarToolbarAttributes[K] } & { [K in keyof UiCalendarToolbar & keyof UiCalendarToolbarAttributes as `prop:${K}`]?: UiCalendarToolbar[K] };
        "ui-calendar-week-view": Omit<UiCalendarWeekView, keyof UiCalendarWeekViewAttributes> & { [K in keyof UiCalendarWeekView & keyof UiCalendarWeekViewAttributes]?: UiCalendarWeekView[K] } & { [K in keyof UiCalendarWeekView & keyof UiCalendarWeekViewAttributes as `attr:${K}`]?: UiCalendarWeekViewAttributes[K] } & { [K in keyof UiCalendarWeekView & keyof UiCalendarWeekViewAttributes as `prop:${K}`]?: UiCalendarWeekView[K] };
        "ui-card": Omit<UiCard, keyof UiCardAttributes> & { [K in keyof UiCard & keyof UiCardAttributes]?: UiCard[K] } & { [K in keyof UiCard & keyof UiCardAttributes as `attr:${K}`]?: UiCardAttributes[K] } & { [K in keyof UiCard & keyof UiCardAttributes as `prop:${K}`]?: UiCard[K] };
        "ui-checklist": Omit<UiChecklist, keyof UiChecklistAttributes> & { [K in keyof UiChecklist & keyof UiChecklistAttributes]?: UiChecklist[K] } & { [K in keyof UiChecklist & keyof UiChecklistAttributes as `attr:${K}`]?: UiChecklistAttributes[K] } & { [K in keyof UiChecklist & keyof UiChecklistAttributes as `prop:${K}`]?: UiChecklist[K] };
        "ui-checklist-item": Omit<UiChecklistItem, keyof UiChecklistItemAttributes> & { [K in keyof UiChecklistItem & keyof UiChecklistItemAttributes]?: UiChecklistItem[K] } & { [K in keyof UiChecklistItem & keyof UiChecklistItemAttributes as `attr:${K}`]?: UiChecklistItemAttributes[K] } & { [K in keyof UiChecklistItem & keyof UiChecklistItemAttributes as `prop:${K}`]?: UiChecklistItem[K] };
        "ui-chip": Omit<UiChip, keyof UiChipAttributes> & { [K in keyof UiChip & keyof UiChipAttributes]?: UiChip[K] } & { [K in keyof UiChip & keyof UiChipAttributes as `attr:${K}`]?: UiChipAttributes[K] } & { [K in keyof UiChip & keyof UiChipAttributes as `prop:${K}`]?: UiChip[K] };
        "ui-input": Omit<UiInput, keyof UiInputAttributes> & { [K in keyof UiInput & keyof UiInputAttributes]?: UiInput[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `attr:${K}`]?: UiInputAttributes[K] } & { [K in keyof UiInput & keyof UiInputAttributes as `prop:${K}`]?: UiInput[K] };
        "ui-kanban-board": UiKanbanBoard;
        "ui-kanban-card": Omit<UiKanbanCard, keyof UiKanbanCardAttributes> & { [K in keyof UiKanbanCard & keyof UiKanbanCardAttributes]?: UiKanbanCard[K] } & { [K in keyof UiKanbanCard & keyof UiKanbanCardAttributes as `attr:${K}`]?: UiKanbanCardAttributes[K] } & { [K in keyof UiKanbanCard & keyof UiKanbanCardAttributes as `prop:${K}`]?: UiKanbanCard[K] };
        "ui-kanban-column": Omit<UiKanbanColumn, keyof UiKanbanColumnAttributes> & { [K in keyof UiKanbanColumn & keyof UiKanbanColumnAttributes]?: UiKanbanColumn[K] } & { [K in keyof UiKanbanColumn & keyof UiKanbanColumnAttributes as `attr:${K}`]?: UiKanbanColumnAttributes[K] } & { [K in keyof UiKanbanColumn & keyof UiKanbanColumnAttributes as `prop:${K}`]?: UiKanbanColumn[K] };
        "ui-page-section": UiPageSection;
        "ui-panel": Omit<UiPanel, keyof UiPanelAttributes> & { [K in keyof UiPanel & keyof UiPanelAttributes]?: UiPanel[K] } & { [K in keyof UiPanel & keyof UiPanelAttributes as `attr:${K}`]?: UiPanelAttributes[K] } & { [K in keyof UiPanel & keyof UiPanelAttributes as `prop:${K}`]?: UiPanel[K] };
        "ui-select": Omit<UiSelect, keyof UiSelectAttributes> & { [K in keyof UiSelect & keyof UiSelectAttributes]?: UiSelect[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `attr:${K}`]?: UiSelectAttributes[K] } & { [K in keyof UiSelect & keyof UiSelectAttributes as `prop:${K}`]?: UiSelect[K] };
        "ui-stack": Omit<UiStack, keyof UiStackAttributes> & { [K in keyof UiStack & keyof UiStackAttributes]?: UiStack[K] } & { [K in keyof UiStack & keyof UiStackAttributes as `attr:${K}`]?: UiStackAttributes[K] } & { [K in keyof UiStack & keyof UiStackAttributes as `prop:${K}`]?: UiStack[K] };
        "ui-task-list": Omit<UiTaskList, keyof UiTaskListAttributes> & { [K in keyof UiTaskList & keyof UiTaskListAttributes]?: UiTaskList[K] } & { [K in keyof UiTaskList & keyof UiTaskListAttributes as `attr:${K}`]?: UiTaskListAttributes[K] } & { [K in keyof UiTaskList & keyof UiTaskListAttributes as `prop:${K}`]?: UiTaskList[K] };
        "ui-task-list-item": Omit<UiTaskListItem, keyof UiTaskListItemAttributes> & { [K in keyof UiTaskListItem & keyof UiTaskListItemAttributes]?: UiTaskListItem[K] } & { [K in keyof UiTaskListItem & keyof UiTaskListItemAttributes as `attr:${K}`]?: UiTaskListItemAttributes[K] } & { [K in keyof UiTaskListItem & keyof UiTaskListItemAttributes as `prop:${K}`]?: UiTaskListItem[K] };
        "ui-textarea": Omit<UiTextarea, keyof UiTextareaAttributes> & { [K in keyof UiTextarea & keyof UiTextareaAttributes]?: UiTextarea[K] } & { [K in keyof UiTextarea & keyof UiTextareaAttributes as `attr:${K}`]?: UiTextareaAttributes[K] } & { [K in keyof UiTextarea & keyof UiTextareaAttributes as `prop:${K}`]?: UiTextarea[K] };
        "ui-toolbar": Omit<UiToolbar, keyof UiToolbarAttributes> & { [K in keyof UiToolbar & keyof UiToolbarAttributes]?: UiToolbar[K] } & { [K in keyof UiToolbar & keyof UiToolbarAttributes as `attr:${K}`]?: UiToolbarAttributes[K] } & { [K in keyof UiToolbar & keyof UiToolbarAttributes as `prop:${K}`]?: UiToolbar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-activity-timeline": LocalJSX.IntrinsicElements["ui-activity-timeline"] & JSXBase.HTMLAttributes<HTMLUiActivityTimelineElement>;
            "ui-activity-timeline-item": LocalJSX.IntrinsicElements["ui-activity-timeline-item"] & JSXBase.HTMLAttributes<HTMLUiActivityTimelineItemElement>;
            "ui-badge": LocalJSX.IntrinsicElements["ui-badge"] & JSXBase.HTMLAttributes<HTMLUiBadgeElement>;
            "ui-button": LocalJSX.IntrinsicElements["ui-button"] & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-calendar": LocalJSX.IntrinsicElements["ui-calendar"] & JSXBase.HTMLAttributes<HTMLUiCalendarElement>;
            "ui-calendar-day-cell": LocalJSX.IntrinsicElements["ui-calendar-day-cell"] & JSXBase.HTMLAttributes<HTMLUiCalendarDayCellElement>;
            "ui-calendar-day-view": LocalJSX.IntrinsicElements["ui-calendar-day-view"] & JSXBase.HTMLAttributes<HTMLUiCalendarDayViewElement>;
            "ui-calendar-event-chip": LocalJSX.IntrinsicElements["ui-calendar-event-chip"] & JSXBase.HTMLAttributes<HTMLUiCalendarEventChipElement>;
            "ui-calendar-month-view": LocalJSX.IntrinsicElements["ui-calendar-month-view"] & JSXBase.HTMLAttributes<HTMLUiCalendarMonthViewElement>;
            "ui-calendar-toolbar": LocalJSX.IntrinsicElements["ui-calendar-toolbar"] & JSXBase.HTMLAttributes<HTMLUiCalendarToolbarElement>;
            "ui-calendar-week-view": LocalJSX.IntrinsicElements["ui-calendar-week-view"] & JSXBase.HTMLAttributes<HTMLUiCalendarWeekViewElement>;
            "ui-card": LocalJSX.IntrinsicElements["ui-card"] & JSXBase.HTMLAttributes<HTMLUiCardElement>;
            "ui-checklist": LocalJSX.IntrinsicElements["ui-checklist"] & JSXBase.HTMLAttributes<HTMLUiChecklistElement>;
            "ui-checklist-item": LocalJSX.IntrinsicElements["ui-checklist-item"] & JSXBase.HTMLAttributes<HTMLUiChecklistItemElement>;
            "ui-chip": LocalJSX.IntrinsicElements["ui-chip"] & JSXBase.HTMLAttributes<HTMLUiChipElement>;
            "ui-input": LocalJSX.IntrinsicElements["ui-input"] & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-kanban-board": LocalJSX.IntrinsicElements["ui-kanban-board"] & JSXBase.HTMLAttributes<HTMLUiKanbanBoardElement>;
            "ui-kanban-card": LocalJSX.IntrinsicElements["ui-kanban-card"] & JSXBase.HTMLAttributes<HTMLUiKanbanCardElement>;
            "ui-kanban-column": LocalJSX.IntrinsicElements["ui-kanban-column"] & JSXBase.HTMLAttributes<HTMLUiKanbanColumnElement>;
            "ui-page-section": LocalJSX.IntrinsicElements["ui-page-section"] & JSXBase.HTMLAttributes<HTMLUiPageSectionElement>;
            "ui-panel": LocalJSX.IntrinsicElements["ui-panel"] & JSXBase.HTMLAttributes<HTMLUiPanelElement>;
            "ui-select": LocalJSX.IntrinsicElements["ui-select"] & JSXBase.HTMLAttributes<HTMLUiSelectElement>;
            "ui-stack": LocalJSX.IntrinsicElements["ui-stack"] & JSXBase.HTMLAttributes<HTMLUiStackElement>;
            "ui-task-list": LocalJSX.IntrinsicElements["ui-task-list"] & JSXBase.HTMLAttributes<HTMLUiTaskListElement>;
            "ui-task-list-item": LocalJSX.IntrinsicElements["ui-task-list-item"] & JSXBase.HTMLAttributes<HTMLUiTaskListItemElement>;
            "ui-textarea": LocalJSX.IntrinsicElements["ui-textarea"] & JSXBase.HTMLAttributes<HTMLUiTextareaElement>;
            "ui-toolbar": LocalJSX.IntrinsicElements["ui-toolbar"] & JSXBase.HTMLAttributes<HTMLUiToolbarElement>;
        }
    }
}
